DCHQ_VERSION: '1.0'

OUTBOUND_DEVISE_EMAIL: 'postmaster@mg.divespearandsport.com.au'
DEFAULT_PAGINATION: '50'

WALK_IN_EMAIL: 'walkin@emaildomain.com'

XERO_CONSUMER_KEY:    'PFAT1FDOWRIPTUCOEERE67PFVBVYXR'
XERO_CONSUMER_SECRET: '74MQXTCXFWP94TEFMDS8XWN0IZA22R'

STRIPE_PUBLIC_KEY: ''
STRIPE_API_KEY:    ''

company.logo.image.url: '/lib/assets/DSS_LOGO.png'
company.outbound_email: 'postmaster@mg.divespearandsport.com.au'

HOST: 'https://demo.divecentrehq.com'
APP_NAME: dchq_core
SCUBA_TRIBE_KEY: ''


secret_key: 'Pdm96B2]PX#h49FApaUcPt^Yd8A+8NnPmsJ{cp2A4bWeq3R#'
SECRET_KEY: 'Pdm96B2]PX#h49FApaUcPt^Yd8A+8NnPmsJ{cp2A4bWeq3R#'
MAILGUN_API_KEY: 'key-fa50b766584dcc1774e69f5753892982'
MAILGUN_DOMAIN: 'mg.divespearandsport.com.au'
MAILGUN_PUBLIC_KEY: 'pubkey-44b58f37f96abb6bea7c5080684cd946'
MAILGUN_SMTP_LOGIN: 'postmaster@mg.divespearandsport.com.au'
MAILGUN_SMTP_PASSWORD: 'DiveSS2015'
MAILGUN_SMTP_PORT: '587'
MAILGUN_SMTP_SERVER: 'smtp.mailgun.org'
SECRET_TOKEN: 'Pdm96B2]PX#h49FApaUcPt^Yd8A+8NnPmsJ{cp2A4bWeq3R#'
staging:
  SECRET_KEY: 'Pdm96B2]PX#h49FApaUcPt^Yd8A+8NnPmsJ{cp2A4bWeq3R#'

production:
  SECRET_KEY: <%= ENV["SECRET_TOKEN"] %>
